### ISSUE TITLE
error

### ISSUE THREAD

**Issue by damondiamond** [Freddywhest/VertusBot#1]
| ERROR | [vertus] | vertus_d | ❗️Unknown error during Authorization: Error: Bytes or str expected, not Number

**Comment by yurayu1985** [comment]
| ERROR | [vertus] | vertus_d | ❗️Unknown error during Authorization: Error: Bytes or str expected, not Number

**Comment by shelllshock** [comment]
same

**Comment by Freddywhest** [comment]
Error fixed, update it
